superpoint:
  max_keypoints: 3000
  keypoint_threshold: 0.01
  remove_borders: 4
  input_tensor_names:
    - "image"
  output_tensor_names:
    - "scores"
    - "descriptors"
  onnx_file: "superpoint_v1.onnx"
  engine_file: "superpoint_v1.engine"
  dla_core: -1

superpoint_lightglue:
  image_width: 320
  image_height: 240
  filter_threshold: 0.1
  depth_confidence: -1
  width_confidence: -1
  input_tensor_names:
    - "keypoints0"
    - "keypoints1"
    - "descriptors0"
    - "descriptors1"
  output_tensor_names:
    - "scores"
  onnx_file: "superpoint_lightglue.onnx"
  engine_file: "superpoint_lightglue.engine"
  dla_core: -1

# Camera extrinsics use world_to_camera:
# X_camera = R_world_to_camera * X_world + t_world_to_camera
cameras:
  rgb:
    intrinsic: [606.97900390625, 0.0, 320.3143615722656,
                0.0, 607.1318359375, 247.97427368164062,
                0.0, 0.0, 1.0]
    distortion: [0.0, 0.0, 0.0, 0.0, 0.0]
    rotation: [1.0, 0.0, 0.0,
               0.0, 1.0, 0.0,
               0.0, 0.0, 1.0]
    translation: [0.0, 0.0, 0.0]
  ir:
    intrinsic: [593.946114205786, 0.0, 322.242307522658,
                0.0, 592.545920338569, 264.298408236226,
                0.0, 0.0, 1.0]
    distortion: [0.0, 0.0, 0.0, 0.0, 0.0]
    rotation: [1.0, 0.0, 0.0,
               0.0, 1.0, 0.0,
               0.0, 0.0, 1.0]
    translation: [-0.036, 0.03, -0.009]
